---
parameters: {}
environment: {}
packages:
  - name: discord
    parameters: {}
    environment: {}
    functions:
      - name: interaction 
        main: 'Main'
        runtime: 'go:1.20'
        web: raw
        environment:
          DISCORD_TOKEN: "${DISCORD_TOKEN}"
          DISCORD_APP_PUBLIC_KEY: "${DISCORD_APP_PUBLIC_KEY}"
        parameters: {}
