[package]
name = "yeetcode"
version = "0.1.0"
edition = "2021"

[dependencies]
dropshot = "0.12.0"
ed25519-dalek = "2.1.1"
hex = "0.4.3"
hyper = "1.4.1"
reqwest = "0.12.8"
schemars = "0.8.21"
serde = "1.0.210"
serde_json = "1.0.128"
tokio = "1.40.0"
